### ISSUE TITLE
opencv-python install error

### ISSUE THREAD

**Issue by Hobeom** [esemeniuc/openpose-docker#16]
Step 3/10 : RUN pip3 install numpy opencv-python
 ---> Running in 8eb3fe083088
Collecting numpy
  Downloading https://files.pythonhosted.org/packages/b8/e5/a64ef44a85397ba3c377f6be9c02f3cb3e18023f8c89850dd319e7945521/numpy-1.19.2-cp36-cp36m-manylinux1_x86_64.whl (13.4MB)
Collecting opencv-python
  Downloading https://files.pythonhosted.org/packages/77/f5/49f034f8d109efcf9b7e98fbc051878b83b2f02a1c73f92bbd37f317288e/opencv-python-4.4.0.42.tar.gz (88.9MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kghitlq6/opencv-python/
The command '/bin/sh -c pip3 install numpy opencv-python' returned a non-zero code: 1

**Comment by Hobeom** [comment]
I did install opencv-python==4.0.0.21

**Comment by julrog** [comment]
I added:
`RUN python3 -m pip install --upgrade pip`
Before the line on which the error occurs in the docker file, which fixed this error.
But I then had some issues in step 10/11, but maybe this is a different issue.
