### ISSUE TITLE
Error : start docker env. : Unable to find image 'openpose_v1:latest' locally

### ISSUE THREAD

**Issue by joong925** [esemeniuc/openpose-docker#17]
Hi, 
i tried to run docker after 'build the image using dockerfile', but i got an error from 'start docker env.'

Error below :

sudo docker run --gpus all --name openpose -it openpose_v1:latest /bin/bash

>Unable to find image 'openpose_v1:latest' locally
docker: Error response from daemon: pull access denied for openpose_v1, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

thank you for helping.

**Comment by esemeniuc** [comment]
Sorry I had a bad PR, I've reverted it, please try again
