### ISSUE TITLE
Quick start face & hands example doesn't work with Dockerfile

### ISSUE THREAD

**Issue by thommiano** [esemeniuc/openpose-docker#3]
I was able to build the image without any problems. My host is Ubuntu 16, and I have 4 GTX TitanX GPUs.
```
docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 openpose
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand
```
> Starting OpenPose demo...
> Configuring OpenPose...
> Starting thread(s)...
> Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
> Unable to init server: Could not connect: Connection refused
> (OpenPose 1.4.0:13): Gtk-WARNING **: 14:24:40.539: cannot open display:
> E0503 14:24:40.540756    29 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
> Segmentation fault (core dumped)

I thought the issue may have to do with restricting the GPUs, so I reran the container allowing all GPUs and I still got basically the same error:
```
root@e24603e44435:/openpose# ./build/examples/openpose/openpose.bin --video
```
>examples/media/video.avi --face --hand
>Starting OpenPose demo...
>Configuring OpenPose...
>Starting thread(s)...
>Auto-detecting all available GPUs... Detected 4 GPU(s), using 4 of them starting at GPU 0.
>Unable to init server: Could not connect: Connection refused
>(OpenPose 1.4.0:13): Gtk-WARNING **: 14:35:09.111: cannot open display:
>E0503 14:35:09.112191    30 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
>E0503 14:35:09.112211    29 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
>E0503 14:35:09.112223    31 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
>Segmentation fault (core dumped)

**Comment by esemeniuc** [comment]
I haven't tested with hands or face, just the normal body. What happens when you run the compiled examples (CPP API)?

**Comment by thommiano** [comment]
I believe the problem was that I was running those commands on a remote server that I was connected to via SSH. Turning off the display and rendering (i.e., `--display 0 --render_pose 0`) solved the problem.

Since display and rendering is turned off, you also have to include a write out flag, e.g., `--write_json output/`

**Comment by kjacks21** [comment]
@thommiano I'm running docker on my host machine and I have the same issue. Turning off display resolved the issue, though you can still render the video and view it later. I wonder, @esemeniuc, if there is a way to fix this. If not, it may be worth while to add something to the readme saying this is the case.
