### ISSUE TITLE
I pull the image with the url of your dockerfile, but I didn't work

### ISSUE THREAD

**Issue by Ai-is-light** [esemeniuc/openpose-docker#8]

**Comment by Ai-is-light** [comment]
root@057ac0a675cb:/# python
Python 2.7.15+ (default, Nov 27 2018, 23:36:35)
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import caffe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named caffe
>>> exit()
root@057ac0a675cb:/# which caffe
root@057ac0a675cb:/# cd openpose
root@057ac0a675cb:/openpose# ls
3rdparty  CMakeLists.txt  LICENSE  README.md  build  cmake  doc  examples  include  models  python  scripts  src
root@057ac0a675cb:/openpose# cd build/
root@057ac0a675cb:/openpose/build# ls
3rdparty        CMakeFiles  caffe  cmake_install.cmake    detect_cuda_archs.cu  python
CMakeCache.txt  Makefile    cmake  cmake_uninstall.cmake  examples              src
root@057ac0a675cb:/openpose/build# nvidia-smi
bash: nvidia-smi: command not found
root@057ac0a675cb:/openpose/build#

**Comment by Ai-is-light** [comment]
[root@ ~]# docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 cwaffles/openpose
docker: Error response from daemon: Unknown runtime specified nvidia.
See 'docker run --help'.
[root@TENCENT64 ~]#

**Comment by esemeniuc** [comment]
You need to install the nvidia runtime from here (https://github.com/NVIDIA/nvidia-docker#quickstart) as per the instructions
