### ISSUE TITLE
Difference between cwaffles/openpose and cwaffles/openpose-python

### ISSUE THREAD

**Issue by kjacks21** [esemeniuc/openpose-docker#9]
I'm fairly new to docker so apologies if this is obvious. I ran `docker pull cwaffles/openpose` and it downloaded fine, but when I ran your tutorial line

`docker run -it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=0 cwaffles/openpose-python`

it downloaded `cwaffles/openpose-python`. Is there a difference between the two? Which one should we be using?

**Comment by esemeniuc** [comment]
Good catch, sorry openpose-python was my personal image, cwaffles/openpose is the correct one.
I've updated the readme :)
